spring:
    application:
        name: config-server

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-client: true
        service-url:
            default-zone: http://localhost:8761/eureka
